package generatepostman








































}	log.Printf("Postman collection generated: %s", *output)	}		log.Fatalf("generate postman failed: %v", err)	if err := postmangen.GenerateAuto(context.Background(), cfg); err != nil {	}		},			},				"folderStrategy": "Tags",			Options: map[string]string{		Postman: postmangen.PostmanConfig{		SwagOutputDir:     "cmd/postman",		Pretty:            *pretty,		CollectionName:    *collection,		OutputPath:        *output,		SwaggerInputPath:  *swaggerInput,		MainFile:          *mainFile,		WorkingDir:        ".",	cfg := postmangen.AutoConfig{	flag.Parse()	)		pretty       = flag.Bool("pretty", true, "pretty print output")		mainFile     = flag.String("main-file", "cmd/main.go", "path to your main.go")		collection   = flag.String("collection-name", "Test API", "collection name")		output       = flag.String("output", "cmd/postman/postman_collection.json", "output path")		swaggerInput = flag.String("swagger-input", "", "optional openapi/swagger file path")	var (func main() {)	postmangen "github.com/learncodexx/autogenpostman"	"log"	"flag"	"context"import (package main